name: CI/CD Pipeline (push)

on:
  push:
    branches:
      - main
      - update_workflow
  # pull_request:
  #   branches:
  #     - main
  #     - update
  workflow_dispatch:

jobs:
    classification_api_test_app:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11.1'

        - name: Create venv
          uses: ./.github/workflows/common.yml@prepare_venv
            
        - name: Install tox
          run: pip install --user tox

        - name: Running app tests
          run: |
            cd classification_api
            tox

    deploy_to_railway:
      runs-on: ubuntu-latest
      needs: classification_api_test_app
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: |
          cd classification_api
          railway up --service ${{ secrets.RAILWAY_SERVICE_ID_TITANIC }} --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TITANIC_PROJ_TOKEN }}
        
