name: CI/CD Pipeline (push)

on:
  push:
    branches:
      - main
      - update_workflow
  # pull_request:
  #   branches:
  #     - main
  #     - update
  workflow_dispatch:

jobs:
    classification_api_test_app:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11.1'

        - name: Create venv
          run: |
            python -m venv model_packaging/venv
            source model_packaging/venv/bin/activate
            pip install --upgrade pip
            
        - name: Set KAGGLE_CONFIG_DIR #set where kaggle looks for api credentials to download dataset
          run: |
            echo "KAGGLE_CONFIG_DIR=/home/runner/tmp/.kaggle" >> "$GITHUB_ENV"
        - name: Download dataset
          run: | 
            pip install kaggle 
            mkdir -p /home/runner/tmp/.kaggle
            echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > /home/runner/tmp/.kaggle/kaggle.json
            chmod 600 /home/runner/tmp/.kaggle/kaggle.json
            cat $GITHUB_ENV
            echo "KAGGLE_CONFIG_DIR is ${{ env.KAGGLE_CONFIG_DIR }}"
            
            kaggle competitions download titanic -p package/classification_model/datasets

        # - name: Install tox
        #   run: pip install --user tox

        # - name: Running app tests
        #   run: |
        #     cd classification_api
        #     tox

    # deploy_to_railway:
    #   runs-on: ubuntu-latest
    #   needs: classification_api_test_app
    #   steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2
        
    #   - name: Use Node 16
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: '16.x'

    #   - name: Install Railway CLI
    #     run: npm install -g @railway/cli

    #   - name: Deploy to Railway
    #     run: |
    #       cd classification_api
    #       railway up --service ${{ secrets.RAILWAY_SERVICE_ID_TITANIC }} --detach
    #     env:
    #       RAILWAY_TOKEN: ${{ secrets.RAILWAY_TITANIC_PROJ_TOKEN }}
        
